#!/usr/bin/env python3
# -*- coding: utf-8 -*-

from __future__ import annotations

from pathlib import Path
from typing import Dict, List


REPO = Path("/workspace/Obsidian-Eg")
DOCS = Path("/workspace/.trae/documents")


def _p(*parts: str) -> Path:
    return REPO.joinpath(*parts)


SCOPES: List[Dict[str, object]] = [
    {
        "scope_id": "batch23",
        "display_batch_id": "23",
        "directory": "Wiki/L0_基础词",
        "slice_start": 2200,
        "slice_end": 2300,
        "list_path": _p(".trae", "batches", "batch23_files.txt"),
        "report_path": _p(".trae", "reports", "第23批次基础词2201-2300_6.5-6.6_处理报告.md"),
        "plan_doc": DOCS / "第23批次基础词2201-2300_6.5-6.6句型与语料回填_执行计划.md",
        "group": "executed",
        "has_existing_report": True,
        "unknown_before": 174,
    },
    {
        "scope_id": "batch26",
        "display_batch_id": "26",
        "directory": "Wiki/L0_基础词",
        "slice_start": 2500,
        "slice_end": 2600,
        "list_path": _p(".trae", "batches", "batch26_files.txt"),
        "report_path": _p(".trae", "reports", "第26批次基础词2501-2600_6.5-6.6_处理报告.md"),
        "plan_doc": DOCS / "第26批次基础词2501-2600_6.5-6.6句型与语料回填_执行计划.md",
        "group": "executed",
        "has_existing_report": True,
        "unknown_before": 233,
    },
    {
        "scope_id": "batch28",
        "display_batch_id": "28",
        "directory": "Wiki/L0_超纲词",
        "slice_start": 100,
        "slice_end": 200,
        "list_path": _p(".trae", "batches", "batch28_files.txt"),
        "report_path": _p(".trae", "reports", "第28批次超纲词101-200_6.5-6.6_处理报告.md"),
        "plan_doc": DOCS / "第28批次超纲词101-200_6.5-6.6句型与语料回填_执行计划.md",
        "group": "executed",
        "has_existing_report": True,
        "unknown_before": 129,
    },
    {
        "scope_id": "batch30",
        "display_batch_id": "30",
        "directory": "Wiki/L0_基础词",
        "slice_start": 2900,
        "slice_end": 3000,
        "list_path": _p(".trae", "batches", "batch30_files.txt"),
        "report_path": _p(".trae", "reports", "第30批次2901-3000_6.5-6.6_处理报告.md"),
        "plan_doc": DOCS / "第30批次2901-3000_6.5-6.6句型与语料回填_执行计划.md",
        "group": "executed",
        "has_existing_report": True,
        "unknown_before": 206,
    },
    {
        "scope_id": "batch32",
        "display_batch_id": "32",
        "directory": "Wiki/L0_超纲词",
        "slice_start": 300,
        "slice_end": 400,
        "list_path": _p(".trae", "batches", "batch32_files.txt"),
        "report_path": _p(".trae", "reports", "第32批次超纲词301-400_6.5-6.6_处理报告.md"),
        "plan_doc": DOCS / "第32批次超纲词301-400_6.5-6.6句型与语料回填_执行计划.md",
        "group": "executed",
        "has_existing_report": True,
        "unknown_before": 134,
    },
    {
        "scope_id": "batch36",
        "display_batch_id": "36",
        "directory": "Wiki/L0_超纲词",
        "slice_start": 500,
        "slice_end": 600,
        "list_path": _p(".trae", "batches", "batch36_files.txt"),
        "report_path": _p(".trae", "reports", "第36批次超纲词501-600_6.5-6.6_处理报告.md"),
        "plan_doc": DOCS / "第36批次超纲词501-600_6.5-6.6句型与语料回填_执行计划.md",
        "group": "executed",
        "has_existing_report": True,
        "unknown_before": 129,
    },
    {
        "scope_id": "batch38",
        "display_batch_id": "38",
        "directory": "Wiki/L0_超纲词",
        "slice_start": 700,
        "slice_end": 800,
        "list_path": _p(".trae", "batches", "batch38_files.txt"),
        "report_path": _p(".trae", "reports", "第38批次超纲词701-800_6.5-6.6_处理报告.md"),
        "plan_doc": DOCS / "第38批次超纲词701-800_6.5-6.6句型与语料回填_执行计划.md",
        "group": "executed",
        "has_existing_report": True,
        "unknown_before": 104,
    },
    {
        "scope_id": "batch1_basic",
        "display_batch_id": "1",
        "directory": "Wiki/L0_基础词",
        "slice_start": 0,
        "slice_end": 100,
        "list_path": _p(".trae", "batches", "batch1_basic_files.txt"),
        "report_path": _p(".trae", "reports", "第1批次基础词前100个_6.5-6.6_处理报告.md"),
        "plan_doc": DOCS / "第1批次基础词前100个_6.5-6.6句型与语料回填计划.md",
        "group": "early",
        "has_existing_report": False,
    },
    {
        "scope_id": "batch3_basic",
        "display_batch_id": "3",
        "directory": "Wiki/L0_基础词",
        "slice_start": 200,
        "slice_end": 300,
        "list_path": _p(".trae", "batches", "batch3_basic_files.txt"),
        "report_path": _p(".trae", "reports", "第3批次基础词201-300_6.5-6.6_处理报告.md"),
        "plan_doc": DOCS / "第3批次基础词201-300_6.5-6.6句型与语料回填计划.md",
        "group": "early",
        "has_existing_report": False,
    },
    {
        "scope_id": "batch4_basic",
        "display_batch_id": "4",
        "directory": "Wiki/L0_基础词",
        "slice_start": 300,
        "slice_end": 400,
        "list_path": _p(".trae", "batches", "batch4_basic_files.txt"),
        "report_path": _p(".trae", "reports", "第4批次基础词301-400_6.5-6.6_处理报告.md"),
        "plan_doc": DOCS / "第4批次基础词301-400_6.5-6.6句型与语料回填计划.md",
        "group": "early",
        "has_existing_report": False,
    },
    {
        "scope_id": "batch5_set",
        "display_batch_id": "5",
        "directory": "Wiki/L0_单词集合",
        "slice_start": 400,
        "slice_end": 500,
        "list_path": _p(".trae", "batches", "batch5_set_files.txt"),
        "report_path": _p(".trae", "reports", "第5批次单词集合401-500_6.5-6.6_处理报告.md"),
        "plan_doc": DOCS / "第五批次401-500_6.5-6.6句型与语料回填计划.md",
        "group": "early",
        "has_existing_report": False,
    },
    {
        "scope_id": "batch6_basic",
        "display_batch_id": "6",
        "directory": "Wiki/L0_基础词",
        "slice_start": 500,
        "slice_end": 600,
        "list_path": _p(".trae", "batches", "batch6_basic_files.txt"),
        "report_path": _p(".trae", "reports", "第6批次基础词501-600_6.5-6.6_处理报告.md"),
        "plan_doc": DOCS / "第6批次基础词501-600_6.5-6.6句型与语料回填计划.md",
        "group": "early",
        "has_existing_report": False,
    },
    {
        "scope_id": "batch8_basic",
        "display_batch_id": "8",
        "directory": "Wiki/L0_基础词",
        "slice_start": 700,
        "slice_end": 800,
        "list_path": _p(".trae", "batches", "batch8_basic_files.txt"),
        "report_path": _p(".trae", "reports", "第8批次基础词701-800_6.5-6.6_处理报告.md"),
        "plan_doc": DOCS / "第8批次基础词701-800_6.5-6.6句型与语料回填_执行计划.md",
        "group": "early",
        "has_existing_report": False,
    },
    {
        "scope_id": "batch9_basic",
        "display_batch_id": "9",
        "directory": "Wiki/L0_基础词",
        "slice_start": 800,
        "slice_end": 900,
        "list_path": _p(".trae", "batches", "batch9_basic_files.txt"),
        "report_path": _p(".trae", "reports", "第9批次基础词801-900_6.5-6.6_处理报告.md"),
        "plan_doc": DOCS / "第9批次基础词801-900_6.5-6.6句型与语料回填_执行计划.md",
        "group": "early",
        "has_existing_report": False,
    },
    {
        "scope_id": "batch11_basic",
        "display_batch_id": "11",
        "directory": "Wiki/L0_基础词",
        "slice_start": 1000,
        "slice_end": 1100,
        "list_path": _p(".trae", "batches", "batch11_basic_files.txt"),
        "report_path": _p(".trae", "reports", "第11批次基础词1001-1100_6.5-6.6_处理报告.md"),
        "plan_doc": DOCS / "第11批次基础词1001-1100_6.5-6.6句型与语料回填_执行计划.md",
        "group": "early",
        "has_existing_report": False,
    },
    {
        "scope_id": "batch13_basic",
        "display_batch_id": "13",
        "directory": "Wiki/L0_基础词",
        "slice_start": 1200,
        "slice_end": 1300,
        "list_path": _p(".trae", "batches", "batch13_basic_files.txt"),
        "report_path": _p(".trae", "reports", "第13批次基础词1201-1300_6.5-6.6_处理报告.md"),
        "plan_doc": DOCS / "第13批次基础词1201-1300_6.5-6.6句型与语料回填_执行计划.md",
        "group": "early",
        "has_existing_report": False,
    },
    {
        "scope_id": "batch15_basic",
        "display_batch_id": "15",
        "directory": "Wiki/L0_基础词",
        "slice_start": 1400,
        "slice_end": 1500,
        "list_path": _p(".trae", "batches", "batch15_basic_files.txt"),
        "report_path": _p(".trae", "reports", "第15批次基础词1401-1500_6.5-6.6_处理报告.md"),
        "plan_doc": DOCS / "第15批次基础词1401-1500_6.5-6.6句型与语料回填_执行计划.md",
        "group": "early",
        "has_existing_report": False,
    },
    {
        "scope_id": "batch16_set",
        "display_batch_id": "16",
        "directory": "Wiki/L0_单词集合",
        "slice_start": 1500,
        "slice_end": 1600,
        "list_path": _p(".trae", "batches", "batch16_set_files.txt"),
        "report_path": _p(".trae", "reports", "第16批次单词集合1501-1600_6.5-6.6_处理报告.md"),
        "plan_doc": DOCS / "第16批次1501-1600_6.5-6.6句型与语料回填计划.md",
        "group": "early",
        "has_existing_report": False,
    },
    {
        "scope_id": "batch17_basic",
        "display_batch_id": "17",
        "directory": "Wiki/L0_基础词",
        "slice_start": 1600,
        "slice_end": 1700,
        "list_path": _p(".trae", "batches", "batch17_basic_files.txt"),
        "report_path": _p(".trae", "reports", "第17批次基础词1601-1700_6.5-6.6_处理报告.md"),
        "plan_doc": DOCS / "第17批次基础词1601-1700_6.5-6.6句型与语料回填_执行计划.md",
        "group": "early",
        "has_existing_report": False,
    },
    {
        "scope_id": "batch17_set",
        "display_batch_id": "17",
        "directory": "Wiki/L0_单词集合",
        "slice_start": 1600,
        "slice_end": 1700,
        "list_path": _p(".trae", "batches", "batch17_set_files.txt"),
        "report_path": _p(".trae", "reports", "第17批次单词集合1601-1700_6.5-6.6_处理报告.md"),
        "plan_doc": DOCS / "第17批次1601-1700_6.5-6.6句型与语料回填计划.md",
        "group": "early",
        "has_existing_report": False,
    },
    {
        "scope_id": "batch18_set",
        "display_batch_id": "18",
        "directory": "Wiki/L0_单词集合",
        "slice_start": 1700,
        "slice_end": 1800,
        "list_path": _p(".trae", "batches", "batch18_set_files.txt"),
        "report_path": _p(".trae", "reports", "第18批次单词集合1701-1800_6.5-6.6_处理报告.md"),
        "plan_doc": DOCS / "第18批次1701-1800_6.5-6.6句型与语料回填计划.md",
        "group": "early",
        "has_existing_report": False,
    },
    {
        "scope_id": "batch21_basic",
        "display_batch_id": "21",
        "directory": "Wiki/L0_基础词",
        "slice_start": 2000,
        "slice_end": 2100,
        "list_path": _p(".trae", "batches", "batch21_basic_files.txt"),
        "report_path": _p(".trae", "reports", "第21批次基础词2001-2100_6.5-6.6_处理报告.md"),
        "plan_doc": DOCS / "第21批次基础词2001-2100_6.5-6.6句型与语料回填_执行计划.md",
        "group": "early",
        "has_existing_report": False,
    },
]


def get_scopes(group: str = "all") -> List[Dict[str, object]]:
    if group == "all":
        return list(SCOPES)
    return [scope for scope in SCOPES if scope["group"] == group]
